[project]
name = "artisan-worker"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi", "uvicorn[standard]",
  "google-cloud-pubsub","google-cloud-firestore", "google-cloud-storage",
  "pydantic>=2"
]
