[project]
name = "artisan-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "pydantic>=2",
  "google-cloud",
  "google-cloud-firestore",
  "google-cloud-pubsub",
  "google-cloud-storage",
  "python-dotenv",
]

[tool.uvicorn]
factory = false
